# Generated by Django 3.1.3 on 2021-11-20 05:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210301_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_modified_pw',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 20, 5, 3, 47, 453859, tzinfo=utc), verbose_name='パスワード更新日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='UserPasswordHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=150)),
                ('use_from', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
